// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// intensityFunc
double intensityFunc(double t, double baserate);
RcppExport SEXP _simCTMC_intensityFunc(SEXP tSEXP, SEXP baserateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type baserate(baserateSEXP);
    rcpp_result_gen = Rcpp::wrap(intensityFunc(t, baserate));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_simCTMC_intensityFunc", (DL_FUNC) &_simCTMC_intensityFunc, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_simCTMC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
